/* Exclui a Base de Dados: Music caso ela ja exista. */
DROP DATABASE IF EXISTS MUSIC;

/* Criacao da Base de Dados: Music */
create database MUSIC;

/* Determina a base de dados que serao utilizada */
use MUSIC;

/*-------------------------------------------------------------------------------------------------------------*/
/* Criacao das Tabelas */

CREATE TABLE COMPOSITOR (
COD_Compositor INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NomeCompositor VARCHAR(10)
);

CREATE TABLE CONTATO (
COD_Contato INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_Tipo INTEGER NOT NULL,
DescricaoContato VARCHAR(15)
);

CREATE TABLE CANTOR (
COD_Cantor INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NomeCantor VARCHAR(30)
);

CREATE TABLE Envia (
COD_Envio INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_Usuario INTEGER NOT NULL,
COD_Musica INTEGER NOT NULL,
DataDeEnvio DATETIME
);

CREATE TABLE Pertence (
COD_Genero INTEGER NOT NULL,
COD_Musica INTEGER NOT NULL
);

CREATE TABLE TIPODECONTATO (
COD_Tipo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoTipo VARCHAR(15)
);

CREATE TABLE Composta (
COD_Musica INTEGER NOT NULL,
COD_Compositor INTEGER NOT NULL,
DataDaComposicao DATETIME,
FOREIGN KEY(COD_Compositor) REFERENCES COMPOSITOR (COD_Compositor)
);

CREATE TABLE Contem (
COD_Usuario INTEGER NOT NULL,
COD_Contato INTEGER NOT NULL,
FOREIGN KEY(COD_Contato) REFERENCES CONTATO (COD_Contato)
);

CREATE TABLE PAIS (
COD_pais INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoPais VARCHAR(40)
);

CREATE TABLE GENERO (
COD_Genero INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NomeDoGenero VARCHAR(15)
);

CREATE TABLE Possui (
COD_Usuario INTEGER NOT NULL,
COD_Tipo INTEGER NOT NULL
);

CREATE TABLE TIPODEUSUARIO (
COD_Tipo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoTipo VARCHAR(15)
);

CREATE TABLE SeIdentifica (
COD_Nome INTEGER NOT NULL,
COD_Usuario INTEGER NOT NULL
);

CREATE TABLE USUARIO (
COD_Usuario INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Login VARCHAR(45),
Senha VARCHAR(8),
CPF VARCHAR(11),
Sexo VARCHAR(9),
COD_endereco INTEGER NOT NULL,
COD_Genero INTEGER NOT NULL,
FOREIGN KEY(COD_Genero) REFERENCES GENERO (COD_Genero)
);

CREATE TABLE NOME (
COD_Nome INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoNome VARCHAR(50),
COD_ID INTEGER
);

CREATE TABLE TIPODEID (
COD_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoID VARCHAR(15)
);

CREATE TABLE Favorita (
COD_Usuario INTEGER NOT NULL,
COD_Musica INTEGER NOT NULL,
FOREIGN KEY(COD_Usuario) REFERENCES USUARIO (COD_Usuario)
);

CREATE TABLE MUSICA (
COD_Musica INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Titulo VARCHAR(25),
LinkYoutube VARCHAR(45)
);

CREATE TABLE Interpretada (
COD_Musica INTEGER NOT NULL,
COD_Cantor INTEGER NOT NULL,
Gravacao VARCHAR(10),
FOREIGN KEY(COD_Musica) REFERENCES MUSICA (COD_Musica),
FOREIGN KEY(COD_Cantor) REFERENCES CANTOR (COD_Cantor)
);

CREATE TABLE ENDERECO (
COD_endereco INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
COD_pais INTEGER NOT NULL,
COD_Estado INTEGER NOT NULL,
COD_cidade INTEGER NOT NULL,
COD_Bairro INTEGER NOT NULL,
COD_Rua INTEGER NOT NULL,
Numero VARCHAR(6),
FOREIGN KEY(COD_pais) REFERENCES PAIS (COD_pais)
);

CREATE TABLE RUA (
COD_Rua INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoRua VARCHAR(40),
NumCep INTEGER NOT NULL
);

CREATE TABLE CEP (
NumCep INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE CIDADE (
COD_cidade INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescriccaoCidade VARCHAR(40)
);

CREATE TABLE ESTADO (
COD_Estado INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoEstado VARCHAR(40)
);

CREATE TABLE BAIRRO (
COD_Bairro INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DescricaoBairro VARCHAR(40)
);

ALTER TABLE CONTATO ADD FOREIGN KEY(COD_Tipo) REFERENCES TIPODECONTATO (COD_Tipo);
ALTER TABLE Envia ADD FOREIGN KEY(COD_Usuario) REFERENCES USUARIO (COD_Usuario);
ALTER TABLE Envia ADD FOREIGN KEY(COD_Musica) REFERENCES MUSICA (COD_Musica);
ALTER TABLE Pertence ADD FOREIGN KEY(COD_Musica) REFERENCES MUSICA (COD_Musica);
ALTER TABLE Pertence ADD FOREIGN KEY(COD_Genero) REFERENCES GENERO (COD_Genero);
ALTER TABLE Composta ADD FOREIGN KEY(COD_Musica) REFERENCES MUSICA (COD_Musica);
ALTER TABLE Contem ADD FOREIGN KEY(COD_Usuario) REFERENCES USUARIO (COD_Usuario);
ALTER TABLE Possui ADD FOREIGN KEY(COD_Usuario) REFERENCES USUARIO (COD_Usuario);
ALTER TABLE Possui ADD FOREIGN KEY(COD_Tipo) REFERENCES TIPODEUSUARIO (COD_Tipo);
ALTER TABLE SeIdentifica ADD FOREIGN KEY(COD_Nome) REFERENCES NOME (COD_Nome);
ALTER TABLE SeIdentifica ADD FOREIGN KEY(COD_Usuario) REFERENCES USUARIO (COD_Usuario);
ALTER TABLE USUARIO ADD FOREIGN KEY(COD_endereco) REFERENCES ENDERECO (COD_endereco);
ALTER TABLE NOME ADD FOREIGN KEY(COD_ID) REFERENCES TIPODEID (COD_ID);
ALTER TABLE Favorita ADD FOREIGN KEY(COD_Musica) REFERENCES MUSICA (COD_Musica);
ALTER TABLE ENDERECO ADD FOREIGN KEY(COD_Estado) REFERENCES ESTADO (COD_Estado);
ALTER TABLE ENDERECO ADD FOREIGN KEY(COD_cidade) REFERENCES CIDADE (COD_cidade);
ALTER TABLE ENDERECO ADD FOREIGN KEY(COD_Bairro) REFERENCES BAIRRO (COD_Bairro);
ALTER TABLE ENDERECO ADD FOREIGN KEY(COD_Rua) REFERENCES RUA (COD_Rua);
ALTER TABLE RUA ADD FOREIGN KEY(NumCep) REFERENCES CEP (NumCep);
/*-------------------------------------------------------------------------------------------------------------*/